### ISSUE TITLE
Breadcrumb component - code naming

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/wagtail-nhsuk-frontend#108]
The breadcrumb component is referred to as Breadcrumb**s**, this should be singular Breadcrumb, to match the Frontend library.

Only a small issue but for consistency.

**Comment by mikemonteith** [comment]
Important to get these kind of things fixed before we publish a version 1!

**Comment by AdamChrimes** [comment]
Closed - this is done and will be in the next release.
