### ISSUE TITLE
Make it easier to update the Header logo

### ISSUE THREAD

**Issue by damonjagger** [nhsuk/wagtail-nhsuk-frontend#132]
## Proposal
I think it would be useful if site admins or developers could extend the Header component for use cases such as adding an [Organisational Logo](https://www.england.nhs.uk/nhsidentity/identity-guidelines/organisational-logos/).

I think we'd currently have to duplicate the entire template if we wanted to do so?

## Potential solutions
Not given it too much thought, but it would be nice if there were some blocks we could add to/override for things like this. Something like `{% block logo %}` surrounding the logo would allow developers to extend the header and just replace the SVG.

Could also consider updating the [settings](https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/settings/models.py#L27) with a logo_image field, which defaults to NHS when not present.

Be interesting to see other's thoughts on this.

**Comment by mikemonteith** [comment]
The frontend library team are working on changes to the header to allow different logos. We will wait for their updates before integrating anything into this project.

**Comment by AdamChrimes** [comment]
I'm going to try pick this up as part of https://github.com/nhsuk/wagtail-nhsuk-frontend/issues/161

Once its done I'll give you a shout to see if you could test it @damonjagger!

**Comment by DomBaker** [comment]
Two years on I think we have got this work done and ready to merge on a PR 😁 #168

**Comment by damonjagger** [comment]
Amazing, thank you! Will give it a test and let you know how we get on haha.

**Comment by DomBaker** [comment]
hopefully, this issue can be closed 😁, how did you get on with the new org header @damonjagger

**Comment by chrimesdev** [comment]
@DomBaker course its working, I did it
