### ISSUE TITLE
Panel and Grey panel components

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/wagtail-nhsuk-frontend#135]
Currently **Panel** and **Grey panel** are 2 separate components, however, a grey panel is just a color variant of the Panel component. So instead of having them as 2 separate components, there should just be a dropdown within Panel to select the grey variant.

**Comment by AdamChrimes** [comment]
Don't work on this just yet, there is some work to be done with the Promo + Panel component in the NHS.UK frontend so might be no point.

**Comment by mikemonteith** [comment]
Panels are being removed in favour of the card component
