### ISSUE TITLE
Header search field parameters

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/wagtail-nhsuk-frontend#136]
The header search form has it's action attribute hardcoded `<form action="/search/">`. Not all users of this library will have their search endpoint at `/search/`.

The header search input has it's name attribute hardcoded `<input name="search-field>`
Not all users of this library will have their search parameter at `/?search-field=input`.

The Python templates need updating to allow for custom parameters on these fields. This was done with the nunjucks macros on the FE library: https://github.com/nhsuk/nhsuk-frontend/issues/458

**Comment by mikemonteith** [comment]
Looks like this has been addressed in commit https://github.com/nhsuk/wagtail-nhsuk-frontend/commit/2cb5ecb which has been merged to dev but not released yet.

**Comment by AdamChrimes** [comment]
This was fixed!
