### ISSUE TITLE
Could we make inclusion tags work in templates which do not have access to a page context?

### ISSUE THREAD

**Issue by damonjagger** [nhsuk/wagtail-nhsuk-frontend#142]
I noticed that some of the inclusion tags only work if a wagtail page is present in the templates context.

```
page = context['page']
site = page.get_site()
header = HeaderSettings.for_site(site)
```
https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/settings/templatetags/nhsukfrontendsettings_tags.py#L9

Could we make these work in any template, not just ones with the page context present?

Maybe something like

```
request = context['request']
site = Site.find_for_request(request)
header = HeaderSettings.for_site(site)
```
https://docs.wagtail.io/en/latest/reference/pages/model_reference.html#wagtail.core.models.Site.find_for_request

Just been getting around this by passing Site.root_page page context to these pages for now. But I can imagine people may wish to use these in regular Django views/templates.

Maybe this could be a fallback for when the page context isn't present.

**Comment by mikemonteith** [comment]
This is important because not all pages have access to the `Page` object. (e.g 404 page)
The testapp in this repo serves a 500 error for http://localhost:8000/not-found/ due to this issue. (N.B to test the 404 page, you will need to set `DEBUG=False` when in development mode)
