### ISSUE TITLE
Allow blocks inside Care Cards

### ISSUE THREAD

**Issue by beseven** [nhsuk/wagtail-nhsuk-frontend#145]
Following suit from https://github.com/nhsuk/wagtail-nhsuk-frontend/issues/144 and given there is a need for (at least) a Details block inside a care card as part of the work undertaken as part of Improvements to urgent care signposting (Internal: https://jira.service.nhs.uk/browse/TM-715 & https://confluence.service.nhs.uk/display/CIT/TM-386+Fix+a+date+for+Design+Governance+Board) and pain scale work, the following proposal is put forward.

At the moment, the body of our CareCard only allows richtext.
Should we change body to be a streamblock so that other components can go inside the details dropdown?

```
class CareCardBlock(FlattenValueContext, StructBlock):
   ...
    title = CharBlock(required=True)
    body = RichTextBlock(required=True)
   ...
    class Meta:
        template = 'wagtailnhsukfrontend/care_card.html'
```

https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/wagtailnhsukfrontend/blocks.py#L33

**Comment by alexparsons07** [comment]
The Design Working Group discussed this issue on 21/10/19. Feedback as follows:

- Work is being done on using details inside care cards as part of CIT1. Having details inside care card block would allow signposting of users to urgent care: there to reassure and make sure users have the option if they aren't comfortable using 111.

- Design working group suggested that if there is evidence of components within components fulfilling user needs and working well, then to evidence this within an individual component GitHub issue for the service manual team to consider publishing this guidance.

- The service manual team will not create general guidance of how to use components inside components, expectation is that teams should user test and make use of content design and interaction design expertise.
