### ISSUE TITLE
Allow blocks inside panels

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#152]
Add Action link inside the panel stream block (and anything else you think might be immediately beneficial)

Panel and grey panel are duplicates that can be combined

**Comment by bradmorton1** [comment]
@prembonsall grey panel combine has already been worked on, PR just needs resurrecting - https://github.com/nhsuk/wagtail-nhsuk-frontend/pull/140

**Comment by DomBaker** [comment]
Safe to assume this is redundant due to the depreciation of panels.
