### ISSUE TITLE
Header: add the organisational header variants

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/wagtail-nhsuk-frontend#161]
# Organisational header

https://service-manual.nhs.uk/design-system/components/header#organisational-header

- [x] Ability to choose between the standard NHS header or the organisational header
- [x] Ability to change the organisation name and organisation descriptor in admin
- [x] Ability to upload a custom .png/jpg image in admin
- [x] Ability to choose between the blue or white header in admin

Potentially related issue: https://github.com/nhsuk/wagtail-nhsuk-frontend/issues/132

I think this functionality will open up this plugin to more users

**Comment by AdamChrimes** [comment]
Going to have a go at this myself 😎
