### ISSUE TITLE
Review open issues and pull requests and decide what to do with them

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/wagtail-nhsuk-frontend#193]
## Description

- [x] Review open issues and pull requests and decide what to do with them

## Related to

https://github.com/nhsuk/nhsuk-service-manual/issues/1159

**Comment by DomBaker** [comment]
- Started taking a look at the open issues and pull requests related to the wagtail plug-in
- In the process of finding any inconsistencies with the NHS.UK front-end.

**Comment by DomBaker** [comment]
Some of the findings are as followed, 

- Inconsistent naming in relation to components in the Wagtail CMS, for example, Right panel, Left panel
(Naming should be closely coupled with the front-end library for ease of understanding each component).

- Current missing components, Forms, Tables, Nav A to Z, List Panel (More to add).
(In adding these will reduce the main CMS's custom styling and workaround code).

- Backward compatibility
(Getting a better understanding of what will break while rectifying some of these issues, Backward compatibility is somewhat important, but, functionality in line with the latest Front-end Library version is more so).
