### ISSUE TITLE
Deprecation timescales

### ISSUE THREAD

**Issue by dragondave** [nhsuk/wagtail-nhsuk-frontend#195]
What is the likely timescale or version when the deprecated blocks like GreyPanelBlock will be removed?
Could this be documented?

**Comment by dragondave** [comment]
Looks pretty imminent
https://github.com/nhsuk/wagtail-nhsuk-frontend/pull/194

**Comment by mikemonteith** [comment]
I'd guess within the next couple of weeks. We will be releasing a major version upgrade (version 1.0.0) with those deprecated blocks removed - they have been removed from the service manual for a while now.

@dragondave I'd be interested in knowing how much of a headache this is going to be for you to upgrade?

**Comment by dragondave** [comment]
We're investigating now. My gut feeling is that it isn't a major concern. 
Is there an obvious upgrade path?

**Comment by dragondave** [comment]
That's super helpful -- thank you very much for your insight!
