### ISSUE TITLE
Is extending RichText block a problem?

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#2]
```py
class CalloutBlock(RichTextBlock):

    class Meta:
        template = 'wagtailnhsstyle/callout.html'
```

Some wagtail implementations do not use RichText (notable example: nhs.uk).
We should either:
1. Document a workaround
2. Change the implementation to support custom text-input model (e.g markdown)
3. Always extend StructBlock so that implementors can inherit from the class and override the text field.

**Comment by Ross-Clark** [comment]
Using a StructBlock will also give you the control over what **tags** people can use in the components. This would prevent people from inserting images in them .etc

**Comment by AdamChrimes** [comment]
Duplicate of #71
