### ISSUE TITLE
Change "author" of pypi package

### ISSUE THREAD

**Issue by mikemonteith-livi** [nhsuk/wagtail-nhsuk-frontend#226]
The package author is set to `mike.monteith@nhs.net`. This ~person~ email address no longer exists.
Who should be the package owner? Is there a generic "Developers at nhsuk" email account we could use?

https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/7649f717e887aaed0a7c363270e3f584171e64ed/setup.py#L28

**Comment by henocookie** [comment]
@SeanCraig is there a generic NHS.UK Developer email account that could be used here?

**Comment by DomBaker** [comment]
The author changed to me for now
