### ISSUE TITLE
Current wagtail-nhsuk-frontend not compatible with the latest nhsuk-frontend

### ISSUE THREAD

**Issue by chrimesdev** [nhsuk/wagtail-nhsuk-frontend#231]
## Description

We recently noticed that when using the latest version of the `nhsuk-frontend` (6.0.1), it doesn't match up with the current version of the `wagtail-nhsuk-frontend`. 

This is mainly because of the breaking changes found in `nhsuk-frontend` v6.0.0

**Comment by wa-rren-dev** [comment]
Hello, thank you for raising this. We don't have any dev resource in the service manual team at the moment but we'll add this to the backlog to pick up when the team reconvenes.

**Comment by DomBaker** [comment]
Hi Adam, fix for this issue is now in the process of being reviewed, you should be able to update your version of the wagtail-nhsuk-frontend in the coming days. Thanks for raising this.
