### ISSUE TITLE
Github release didn't release to pypi

### ISSUE THREAD

**Issue by mikemonteith-livi** [nhsuk/wagtail-nhsuk-frontend#239]
I'm not sure what's going on, I created a new release in the github UI but it didn't trigger the workflow.

**Comment by mikemonteith-livi** [comment]
Release: https://github.com/nhsuk/wagtail-nhsuk-frontend/releases/tag/v1.4.0

**Comment by DomBaker** [comment]
I'll take a look cheers Mike

**Comment by DomBaker** [comment]
deployed
