### ISSUE TITLE
Allow block templates to be reused as normal template includes

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#38]
We’ve created block templates

```python
class WhateverBlock(StructBlock):
    text = blocks.CharBlock()
    url = blocks.URLBlock()
    
    class Meta:
       template = 'whatever.html'
```

Then in the template html:
```django
<a href="{{ value.url }}">{{ value.text }}</a>
```
---
This is ok if the template is only ever used as a block, but it would be good to let people use the templates directly if they need to:
e.g
```django
{% include "whatever.html" with text="example" url="http://example.com" %}
```

We should work out the cleanest way of supporting both blocks and template includes with minimal duplication of templates

**Comment by wengole** [comment]
Some ideas I've got so far:
* Just document that you need to pass the context in as `value={foo: 'blah', bar: 'blah'}`
* Create a template tag so you can do something like `{% include_frontend ..... %}` and that have logic that does wraps the args in `value={....`

**Comment by mikemonteith** [comment]
Problem is that `value={foo: 'blah', bar: 'blah'}` is not possible directly in a template so people would have to mess about with setting the right context.
`{% include ... with title=page.some_field %}` is nicer than `{% include ... with value=dict_that_needs_to_be_in_context %}`

**Comment by mikemonteith** [comment]
Templatetag would work, but means people have to know about it and understand how it works.

**Comment by mikemonteith** [comment]
I thought we could create generic template includes, and then make all our block templates use it, like this:

`promo_block.html`:
```django
{% include "promo.html" with title=value.title image=value.image %}
```

**Comment by wengole** [comment]
I actually like that idea better. My plan now then is to slightly restructure the templates into `components/` and `blocks/` and have the ones in `blocks` include the ones in `components`. Just to ensure we have a nice directory structure.

**Comment by AdamChrimes** [comment]
This was done in #122
