### ISSUE TITLE
Review streamfield admin interface

### ISSUE THREAD

**Issue by mikemonteith** [nhsuk/wagtail-nhsuk-frontend#62]
Review the wagtail admin interface for streamfields.

- [ ] Should we use the `group` feature?
- [x] Give each block a relevant icon
- [ ] Decide if/how we can link to the service manual from within the wagtail admin

**Comment by AdamChrimes** [comment]
Within the admin interface, components have a placeholder icon - these icons could be customized to be representative of the component.

<img width="620" alt="Screenshot 2019-04-29 at 10 20 54" src="https://user-images.githubusercontent.com/11615501/56887104-84e11f80-6a68-11e9-8ee6-2c422b0f8a9b.png">

**Comment by pflynny** [comment]
It would be worth using the streamfield group feature, that combined with some custom CSS can add a lot of clarity to the interface. 

Adding custom icons can really help ambiguity about what each streamfield is and how it's used. Here's a few I've used before.

<img width="795" alt="Screen Shot 2019-08-12 at 4 29 46 PM" src="https://user-images.githubusercontent.com/519552/62877398-d9aa5c80-bd1e-11e9-955c-c69588d17050.png">

**Comment by mikemonteith** [comment]
I've gone for these wagtail icons as a first-pass. If we feel the need for better icons, they will need to be designed.
![image](https://user-images.githubusercontent.com/227467/67202814-7402dc80-f401-11e9-8d09-b5fe871dddd0.png)
