### ISSUE TITLE
Wagtail admin interface component icons

### ISSUE THREAD

**Issue by sabi98** [nhsuk/wagtail-nhsuk-frontend#78]
Within the admin interface, components have a placeholder icon - these icons could be customized to be representative of the component.

<img width="620" alt="Screenshot 2019-04-29 at 10 20 54" src="https://user-images.githubusercontent.com/11615501/56887104-84e11f80-6a68-11e9-8ee6-2c422b0f8a9b.png">

**Comment by AdamChrimes** [comment]
Duplicate of #62
