### ISSUE TITLE
Missing label in admin for warning callout & capitalisation of letters

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/wagtail-nhsuk-frontend#95]
When in the Wagtail admin and selecting the Warning callout component, the field for the body content does not have a label next to it - it's just a box aligned to the left so I don't know what I am supposed to be entering.

I'm guessing its body content so I would expect the field to have a label of *Body:* similar to other components. (See screenshot)

Also a small thing but for consistency, for the Action link component, do we need to capitalize the first letter so 'Link text' and 'External URL' - also something to note is that the link is always necessarily an external URL. eg. Find a pharmacy is still the NHS website. 

<img width="1421" alt="Screenshot 2019-04-10 at 14 14 43" src="https://user-images.githubusercontent.com/11615501/55881791-3fcd7a00-5b9b-11e9-916d-af380d7915f3.png">

**Comment by AdamChrimes** [comment]
After speaking to Ben and Mike, we may need a 'Title' field on the Warning callout as we want this to be customised - by default (if blank) it will be 'Important'

See example here: https://nhsuk.github.io/nhsuk-frontend/components/warning-callout/index.html

**Comment by Ross-Clark** [comment]
I also noticed a lack of labels on the inset text, which i will fix as a part of this issue

**Comment by AdamChrimes** [comment]
Closed - this is done and will be in the next release.
